# Generated by Django 5.1.1 on 2025-12-09 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KeplerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=21)),
                ('font', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spaceapp.font')),
            ],
        ),
    ]
